name: tiktok_style_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  internet_connection_checker: ^3.0.1
  http: ^1.3.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  video_player: ^2.9.3
  chewie: ^1.10.0
  get_it: ^8.0.3
  dio: ^5.8.0+1
  file_picker: ^9.0.2
  uuid: ^4.5.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  flutter_cache_manager: ^3.3.0
  image: ^4.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^6.3.0
  video_compress: ^3.1.4
  just_audio: ^0.9.46
  injectable: ^2.5.0
  retrofit: ^4.4.2
  crypto: ^3.0.6
  visibility_detector: ^0.4.0+2
  video_player_platform_interface: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
